# Use official Python base image
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy everything into the container
COPY . .

# Install any dependencies (if any)
RUN pip install -r requirements.txt

# Default command (overridable)
CMD ["python", "analyzer.py"]

EXPOSE 5000
